#
# Borland C++ IDE generated makefile
# Generated 12/27/01 at 7:56:29 PM 
#
.AUTODEPEND


#
# Borland C++ tools
#
IMPLIB  = Implib
BCC32   = Bcc32 +BccW32.cfg 
BCC32I  = Bcc32i +BccW32.cfg 
TLINK32 = TLink32
TLIB    = TLib
BRC32   = Brc32
TASM32  = Tasm32
#
# IDE macros
#


#
# Options
#
IDE_LinkFLAGS32 =  -LC:\program files\borland\BCC55\LIB
IDE_ResFLAGS32 = 
LinkerLocalOptsAtW32_WormHoledexe =  -Tpe -aa -V4.0 -c -LC:\PROGRA~1\BORLAND\BCC55\LIB
ResLocalOptsAtW32_WormHoledexe = 
BLocalOptsAtW32_WormHoledexe = 
CompInheritOptsAt_WormHoledexe = -IC:\PROGRA~1\BORLAND\BCC55\INCLUDE;C:\ROUNDA~1\LIBRARY;C:\ROUNDA~1\LIBRARY\3D 
LinkerInheritOptsAt_WormHoledexe = -x
LinkerOptsAt_WormHoledexe = $(LinkerLocalOptsAtW32_WormHoledexe)
ResOptsAt_WormHoledexe = $(ResLocalOptsAtW32_WormHoledexe)
BOptsAt_WormHoledexe = $(BLocalOptsAtW32_WormHoledexe)

#
# Dependency List
#
Dep_WormHole = \
   WormHole.exe

WormHole : BccW32.cfg $(Dep_WormHole)
  echo MakeNode

Dep_WormHoledexe = \
   ssanim.obj\
   settings.obj\
   ssconfig.obj\
   C:\PROGRA~1\BORLAND\BCC55\LIB\noeh32.lib\
   tcamlst.obj\
   linetype.obj\
   polyobj.obj\
   point3d.obj\
   point2d.obj\
   panel3d.obj\
   palshade.obj\
   matrix3d.obj\
   loadtext.obj\
   texttype.obj\
   basecfg.obj\
   OrderOpt.obj\
   baseset.obj\
   printcnl.obj\
   helphint.obj\
   orderfrm.obj\
   tbitmap.obj\
   tobjlist.obj\
   mediadir.obj\
   mediaply.obj\
   tstrlist.obj\
   tcanvas.obj\
   ssthread.obj\
   ssbase.obj\
   metafile.obj\
   sstools.obj\
   printer.obj\
   dib.obj\
   decodgif.obj\
   ssbase.res\
   WormHole.res

WormHole.exe : $(Dep_WormHoledexe)
  $(TLINK32) @&&|
 /v $(IDE_LinkFLAGS32) $(LinkerOptsAt_WormHoledexe) $(LinkerInheritOptsAt_WormHoledexe) +
C:\PROGRA~1\BORLAND\BCC55\LIB\c0w32.obj+
ssanim.obj+
settings.obj+
ssconfig.obj+
tcamlst.obj+
linetype.obj+
polyobj.obj+
point3d.obj+
point2d.obj+
panel3d.obj+
palshade.obj+
matrix3d.obj+
loadtext.obj+
texttype.obj+
basecfg.obj+
OrderOpt.obj+
baseset.obj+
printcnl.obj+
helphint.obj+
orderfrm.obj+
tbitmap.obj+
tobjlist.obj+
mediadir.obj+
mediaply.obj+
tstrlist.obj+
tcanvas.obj+
ssthread.obj+
ssbase.obj+
metafile.obj+
sstools.obj+
printer.obj+
dib.obj+
decodgif.obj
$<,$*
C:\PROGRA~1\BORLAND\BCC55\LIB\noeh32.lib+
C:\PROGRA~1\BORLAND\BCC55\LIB\import32.lib+
C:\PROGRA~1\BORLAND\BCC55\LIB\cw32.lib

ssbase.res+
WormHole.res

|
ssanim.obj :  ssanim.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ssanim.cpp
|

settings.obj :  settings.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ settings.cpp
|

ssconfig.obj :  ssconfig.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ssconfig.cpp
|

tcamlst.obj :  ..\library\tcamlst.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\tcamlst.cpp
|

linetype.obj :  ..\library\3d\linetype.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\3d\linetype.cpp
|

polyobj.obj :  ..\library\3d\polyobj.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\3d\polyobj.cpp
|

point3d.obj :  ..\library\3d\point3d.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\3d\point3d.cpp
|

point2d.obj :  ..\library\3d\point2d.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\3d\point2d.cpp
|

panel3d.obj :  ..\library\3d\panel3d.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\3d\panel3d.cpp
|

palshade.obj :  ..\library\3d\palshade.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\3d\palshade.cpp
|

matrix3d.obj :  ..\library\3d\matrix3d.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\3d\matrix3d.cpp
|

loadtext.obj :  ..\library\3d\loadtext.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\3d\loadtext.cpp
|

texttype.obj :  ..\library\3d\texttype.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\3d\texttype.cpp
|

basecfg.obj :  ..\library\basecfg.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\basecfg.cpp
|

OrderOpt.obj :  ..\library\OrderOpt.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\OrderOpt.cpp
|

baseset.obj :  ..\library\baseset.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\baseset.cpp
|

printcnl.obj :  ..\library\printcnl.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\printcnl.cpp
|

helphint.obj :  ..\library\helphint.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\helphint.cpp
|

orderfrm.obj :  ..\library\orderfrm.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\orderfrm.cpp
|

tbitmap.obj :  ..\library\tbitmap.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\tbitmap.cpp
|

tobjlist.obj :  ..\library\tobjlist.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\tobjlist.cpp
|

mediadir.obj :  ..\library\mediadir.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\mediadir.cpp
|

mediaply.obj :  ..\library\mediaply.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\mediaply.cpp
|

tstrlist.obj :  ..\library\tstrlist.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\tstrlist.cpp
|

tcanvas.obj :  ..\library\tcanvas.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\tcanvas.cpp
|

ssthread.obj :  ..\library\ssthread.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\ssthread.cpp
|

ssbase.obj :  ..\library\ssbase.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\ssbase.cpp
|

metafile.obj :  ..\library\metafile.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\metafile.cpp
|

sstools.obj :  ..\library\sstools.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\sstools.cpp
|

printer.obj :  ..\library\printer.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\printer.cpp
|

dib.obj :  ..\library\dib.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\dib.cpp
|

decodgif.obj :  ..\library\decodgif.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe) -o$@ ..\library\decodgif.cpp
|

ssbase.res :  ..\library\ssbase.rc
  $(BRC32) -R @&&|
 $(IDE_ResFLAGS32) $(ROptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe)  -FO$@ ..\library\ssbase.rc
|
WormHole.res :  WormHole.rc
  $(BRC32) -R @&&|
 $(IDE_ResFLAGS32) $(ROptsAt_WormHoledexe) $(CompInheritOptsAt_WormHoledexe)  -FO$@ WormHole.rc
|
# Compiler configuration file
BccW32.cfg : 
   Copy &&|
-w
-R
-v
-vi
-H
-H=Stars.csm
-W
-wrpt
-wcln
-w-sig
-wucp
-wbbf
-wpin
-wnak
-wdef
-wnod
-wamb
-wuse
-wstv
-wasm
-wamp
-wobs
-wpch
-w-par
-v-
-R-
-x-
-xd-
-RT-
-O2
-g255
-j1
-r
-ff
| $@


