#
# Borland C++ IDE generated makefile
# Generated 1/4/01 at 12:40:59 AM 
#
.AUTODEPEND


#
# Borland C++ tools
#
IMPLIB  = Implib
BCC32   = Bcc32 +BccW32.cfg 
BCC32I  = Bcc32i +BccW32.cfg 
TLINK32 = TLink32
TLIB    = TLib
BRC32   = Brc32
TASM32  = Tasm32
#
# IDE macros
#


#
# Options
#
IDE_LinkFLAGS32 =  -LC:\PROGRA~1\borland\BC5\LIB
IDE_ResFLAGS32 = 
LinkerLocalOptsAtW32_stm2dexe =  -LC:\PROGRA~1\BORLAND\BC5\LIB;C:\RoundA~1\SSLIBRARY -Tpe -aa -V4.0 -c
ResLocalOptsAtW32_stm2dexe = 
BLocalOptsAtW32_stm2dexe = 
CompInheritOptsAt_stm2dexe = -IC:\PROGRA~1\BORLAND\BC5\INCLUDE;C:\RoundA~1\LIBRARY;C:\RoundA~1\LIBRARY\JPEG 
LinkerInheritOptsAt_stm2dexe = -x
LinkerOptsAt_stm2dexe = $(LinkerLocalOptsAtW32_stm2dexe)
ResOptsAt_stm2dexe = $(ResLocalOptsAtW32_stm2dexe)
BOptsAt_stm2dexe = $(BLocalOptsAtW32_stm2dexe)

#
# Dependency List
#
Dep_stm2 = \
   stm2.exe

stm2 : BccW32.cfg $(Dep_stm2)
  echo MakeNode

Dep_stm2dexe = \
   ebook.res\
   viewwnd.obj\
   settings.obj\
   pagelist.obj\
   ebook.obj\
   ..\library\jpeg\jpeg6b.lib\
   tjpeg.obj\
   ttextblk.obj\
   tstartup.obj\
   tobjlist.obj\
   tbitmap.obj\
   printer.obj\
   printcnl.obj\
   metafile.obj\
   mediaply.obj\
   helphint.obj\
   aboutdlg.obj\
   dib.obj\
   decodgif.obj\
   baseset.obj\
   gtools.obj

stm2.exe : $(Dep_stm2dexe)
  $(TLINK32) @&&|
 /v $(IDE_LinkFLAGS32) $(LinkerOptsAt_stm2dexe) $(LinkerInheritOptsAt_stm2dexe) +
C:\PROGRA~1\BORLAND\BC5\LIB\c0w32.obj+
viewwnd.obj+
settings.obj+
pagelist.obj+
ebook.obj+
tjpeg.obj+
ttextblk.obj+
tstartup.obj+
tobjlist.obj+
tbitmap.obj+
printer.obj+
printcnl.obj+
metafile.obj+
mediaply.obj+
helphint.obj+
aboutdlg.obj+
dib.obj+
decodgif.obj+
baseset.obj+
gtools.obj
$<,$*
..\library\jpeg\jpeg6b.lib+
C:\PROGRA~1\BORLAND\BC5\LIB\import32.lib+
C:\PROGRA~1\BORLAND\BC5\LIB\cw32.lib

ebook.res

|
ebook.res :  ebook.rc
  $(BRC32) -R @&&|
 $(IDE_ResFLAGS32) $(ROptsAt_stm2dexe) $(CompInheritOptsAt_stm2dexe)  -FO$@ ebook.rc
|
viewwnd.obj :  viewwnd.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_stm2dexe) $(CompInheritOptsAt_stm2dexe) -o$@ viewwnd.cpp
|

settings.obj :  settings.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_stm2dexe) $(CompInheritOptsAt_stm2dexe) -o$@ settings.cpp
|

pagelist.obj :  pagelist.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_stm2dexe) $(CompInheritOptsAt_stm2dexe) -o$@ pagelist.cpp
|

ebook.obj :  ebook.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_stm2dexe) $(CompInheritOptsAt_stm2dexe) -o$@ ebook.cpp
|

tjpeg.obj :  ..\library\jpeg\tjpeg.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_stm2dexe) $(CompInheritOptsAt_stm2dexe) -o$@ ..\library\jpeg\tjpeg.cpp
|

ttextblk.obj :  ..\library\ttextblk.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_stm2dexe) $(CompInheritOptsAt_stm2dexe) -o$@ ..\library\ttextblk.cpp
|

tstartup.obj :  ..\library\tstartup.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_stm2dexe) $(CompInheritOptsAt_stm2dexe) -o$@ ..\library\tstartup.cpp
|

tobjlist.obj :  ..\library\tobjlist.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_stm2dexe) $(CompInheritOptsAt_stm2dexe) -o$@ ..\library\tobjlist.cpp
|

tbitmap.obj :  ..\library\tbitmap.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_stm2dexe) $(CompInheritOptsAt_stm2dexe) -o$@ ..\library\tbitmap.cpp
|

printer.obj :  ..\library\printer.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_stm2dexe) $(CompInheritOptsAt_stm2dexe) -o$@ ..\library\printer.cpp
|

printcnl.obj :  ..\library\printcnl.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_stm2dexe) $(CompInheritOptsAt_stm2dexe) -o$@ ..\library\printcnl.cpp
|

metafile.obj :  ..\library\metafile.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_stm2dexe) $(CompInheritOptsAt_stm2dexe) -o$@ ..\library\metafile.cpp
|

mediaply.obj :  ..\library\mediaply.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_stm2dexe) $(CompInheritOptsAt_stm2dexe) -o$@ ..\library\mediaply.cpp
|

helphint.obj :  ..\library\helphint.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_stm2dexe) $(CompInheritOptsAt_stm2dexe) -o$@ ..\library\helphint.cpp
|

aboutdlg.obj :  ..\library\aboutdlg.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_stm2dexe) $(CompInheritOptsAt_stm2dexe) -o$@ ..\library\aboutdlg.cpp
|

dib.obj :  ..\library\dib.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_stm2dexe) $(CompInheritOptsAt_stm2dexe) -o$@ ..\library\dib.cpp
|

decodgif.obj :  ..\library\decodgif.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_stm2dexe) $(CompInheritOptsAt_stm2dexe) -o$@ ..\library\decodgif.cpp
|

baseset.obj :  ..\library\baseset.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_stm2dexe) $(CompInheritOptsAt_stm2dexe) -o$@ ..\library\baseset.cpp
|

gtools.obj :  ..\library\gtools.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_stm2dexe) $(CompInheritOptsAt_stm2dexe) -o$@ ..\library\gtools.cpp
|

# Compiler configuration file
BccW32.cfg : 
   Copy &&|
-w
-R
-v
-vi
-H
-H=stm2.csm
-W
| $@


