#
# Borland C++ IDE generated makefile
# Generated 1/28/01 at 12:33:39 AM 
#
.AUTODEPEND


#
# Borland C++ tools
#
IMPLIB  = Implib
BCC32   = Bcc32 +BccW32.cfg 
BCC32I  = Bcc32i +BccW32.cfg 
TLINK32 = iLink32
TLIB    = TLib
BRC32   = Brc32
TASM32  = Tasm32
#
# IDE macros
#


#
# Options
#
IDE_LinkFLAGS32 =  -LC:\PROGRA~1\borland\bcc55\LIB
IDE_ResFLAGS32 = 
LinkerLocalOptsAtW32_ssStartdexe =  -Tpe -aa -V4.0 -c -LC:\PROGRA~1\BORLAND\bcc55\LIB
ResLocalOptsAtW32_ssStartdexe = 
BLocalOptsAtW32_ssStartdexe = 
CompInheritOptsAt_ssStartdexe = -IC:\PROGRA~1\BORLAND\bcc55\INCLUDE;C:\ROUNDA~1\LIBRARY 
LinkerInheritOptsAt_ssStartdexe = -x
LinkerOptsAt_ssStartdexe = $(LinkerLocalOptsAtW32_ssStartdexe)
ResOptsAt_ssStartdexe = $(ResLocalOptsAtW32_ssStartdexe)
BOptsAt_ssStartdexe = $(BLocalOptsAtW32_ssStartdexe)

#
# Dependency List
#
Dep_ssStart = \
   ssStart.exe

ssStart : BccW32.cfg $(Dep_ssStart)
  echo MakeNode

Dep_ssStartdexe = \
   ssconfig.obj\
   settings.obj\
   ssanim.obj\
   OrderOpt.obj\
   baseset.obj\
   printcnl.obj\
   helphint.obj\
   orderfrm.obj\
   tbitmap.obj\
   tobjlist.obj\
   ..\..\progra~1\borland\bcc55\lib\noeh32.lib\
   mediadir.obj\
   mediaply.obj\
   tstrlist.obj\
   tcanvas.obj\
   ssthread.obj\
   ssbase.obj\
   metafile.obj\
   sstools.obj\
   printer.obj\
   dib.obj\
   decodgif.obj\
   ssbase.res\
   ssStart.res

ssStart.exe : $(Dep_ssStartdexe)
  $(TLINK32) @&&|
 /v $(IDE_LinkFLAGS32) $(LinkerOptsAt_ssStartdexe) $(LinkerInheritOptsAt_ssStartdexe) +
C:\PROGRA~1\BORLAND\bcc55\LIB\c0w32.obj+
ssconfig.obj+
settings.obj+
ssanim.obj+
OrderOpt.obj+
baseset.obj+
printcnl.obj+
helphint.obj+
orderfrm.obj+
tbitmap.obj+
tobjlist.obj+
mediadir.obj+
mediaply.obj+
tstrlist.obj+
tcanvas.obj+
ssthread.obj+
ssbase.obj+
metafile.obj+
sstools.obj+
printer.obj+
dib.obj+
decodgif.obj
$<,$*
..\..\progra~1\borland\bcc55\lib\noeh32.lib+
C:\PROGRA~1\BORLAND\bcc55\LIB\import32.lib+
C:\PROGRA~1\BORLAND\bcc55\LIB\cw32.lib

ssbase.res+
ssStart.res

|
ssconfig.obj :  ssconfig.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe) -o$@ ssconfig.cpp
|

settings.obj :  settings.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe) -o$@ settings.cpp
|

ssanim.obj :  ssanim.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe) -o$@ ssanim.cpp
|

OrderOpt.obj :  ..\library\OrderOpt.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe) -o$@ ..\library\OrderOpt.cpp
|

baseset.obj :  ..\library\baseset.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe) -o$@ ..\library\baseset.cpp
|

printcnl.obj :  ..\library\printcnl.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe) -o$@ ..\library\printcnl.cpp
|

helphint.obj :  ..\library\helphint.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe) -o$@ ..\library\helphint.cpp
|

orderfrm.obj :  ..\library\orderfrm.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe) -o$@ ..\library\orderfrm.cpp
|

tbitmap.obj :  ..\library\tbitmap.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe) -o$@ ..\library\tbitmap.cpp
|

tobjlist.obj :  ..\library\tobjlist.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe) -o$@ ..\library\tobjlist.cpp
|

mediadir.obj :  ..\library\mediadir.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe) -o$@ ..\library\mediadir.cpp
|

mediaply.obj :  ..\library\mediaply.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe) -o$@ ..\library\mediaply.cpp
|

tstrlist.obj :  ..\library\tstrlist.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe) -o$@ ..\library\tstrlist.cpp
|

tcanvas.obj :  ..\library\tcanvas.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe) -o$@ ..\library\tcanvas.cpp
|

ssthread.obj :  ..\library\ssthread.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe) -o$@ ..\library\ssthread.cpp
|

ssbase.obj :  ..\library\ssbase.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe) -o$@ ..\library\ssbase.cpp
|

metafile.obj :  ..\library\metafile.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe) -o$@ ..\library\metafile.cpp
|

sstools.obj :  ..\library\sstools.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe) -o$@ ..\library\sstools.cpp
|

printer.obj :  ..\library\printer.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe) -o$@ ..\library\printer.cpp
|

dib.obj :  ..\library\dib.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe) -o$@ ..\library\dib.cpp
|

decodgif.obj :  ..\library\decodgif.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe) -o$@ ..\library\decodgif.cpp
|

ssbase.res :  ..\library\ssbase.rc
  $(BRC32) -R @&&|
 $(IDE_ResFLAGS32) $(ROptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe)  -FO$@ ..\library\ssbase.rc
|
ssStart.res :  ssStart.rc
  $(BRC32) -R @&&|
 $(IDE_ResFLAGS32) $(ROptsAt_ssStartdexe) $(CompInheritOptsAt_ssStartdexe)  -FO$@ ssStart.rc
|
# Compiler configuration file
BccW32.cfg : 
   Copy &&|
-w
-R
-v
-vi
-H
-H=Stars.csm
-W
-wrpt
-wcln
-w-sig
-wucp
-wbbf
-wpin
-wnak
-wdef
-wnod
-wamb
-wuse
-wstv
-wasm
-wamp
-wobs
-wpch
-w-par
-v-
-R-
-x-
-xd-
-RT-
-O2
-g20
-j1
| $@


